In [1]:
!nvidia-smi

Sun Aug 30 03:24:57 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [2]:
from google.colab import files

uploaded = files.upload()

Saving distilbert_phishing_final_project.zip to distilbert_phishing_final_project.zip

In [3]:
!unzip -q distilbert_phishing_final_project.zip

In [4]:
!ls distilbert_phishing_final

config.py	      README.md			    train_distilbert.py
evaluate_external.py  requirements.txt
inference.py	      train_distilbert_colab.ipynb

In [5]:
%cd distilbert_phishing_final

/content/distilbert_phishing_final

In [6]:
!pip install -q -r requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 111.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 37.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 6.26.0 requires huggingface-hub<2.0,>=1.16.0, but you have huggingface-hub 0.36.2 which is incompatible.
diffusers 0.40.0 requires huggingface-hub<2.0,>=1.23.0, but you have huggingface-hub 0.36.2 which is incompatible.

In [7]:
import torch
import transformers
import datasets
import accelerate
import sklearn
import huggingface_hub

print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("Datasets:", datasets.__version__)
print("Accelerate:", accelerate.__version__)
print("Hugging Face Hub:", huggingface_hub.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

PyTorch: 2.11.0+cu128
Transformers: 4.57.6
Datasets: 4.0.0
Accelerate: 1.14.0
Hugging Face Hub: 0.36.2
CUDA available: True
GPU: Tesla T4

In [8]:
from datasets import load_dataset

dataset = load_dataset("zefang-liu/phishing-email-dataset")

print(dataset)

/usr/local/lib/python3.13/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/616 [00:00<?, ?B/s]

Phishing_Email.csv:   0%|          | 0.00/52.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/18650 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['Unnamed: 0', 'Email Text', 'Email Type'],
        num_rows: 18650
    })
})

In [9]:
df = dataset["train"].to_pandas()

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Shape: (18650, 3)

Columns:
['Unnamed: 0', 'Email Text', 'Email Type']

First 5 rows:

,Unnamed: 0,Email Text,Email Type
0,0,"re : 6 . 1100 , disc : uniformitarianism , re ...",Safe Email
1,1,the other side of * galicismos * * galicismo *...,Safe Email
2,2,re : equistar deal tickets are you still avail...,Safe Email
3,3,\nHello I am your hot lil horny toy.\n I am...,Phishing Email
4,4,software at incredibly low prices ( 86 % lower...,Phishing Email

In [10]:
print(df["Email Type"].value_counts())

Email Type
Safe Email        11322
Phishing Email     7328
Name: count, dtype: int64

In [11]:
print(df.isnull().sum())

Unnamed: 0     0
Email Text    16
Email Type     0
dtype: int64

In [12]:
import pandas as pd
import re

# Keep only the columns we actually need
df = df[["Email Text", "Email Type"]].copy()

# Remove emails with no text
df = df.dropna(subset=["Email Text"])

# Convert email text to string
df["Email Text"] = df["Email Text"].astype(str)

# Clean excessive whitespace
df["Email Text"] = df["Email Text"].apply(
    lambda x: re.sub(r"\s+", " ", x).strip()
)

# Remove emails that became empty
df = df[df["Email Text"].str.len() > 0]

# Convert labels to numbers
df["label"] = df["Email Type"].map({
    "Safe Email": 0,
    "Phishing Email": 1
})

# Remove anything that didn't map correctly
df = df.dropna(subset=["label"])

# Convert labels to integer
df["label"] = df["label"].astype(int)

print("Shape after cleaning:", df.shape)
print("\nLabel distribution:")
print(df["label"].value_counts())

print("\nMissing values:")
print(df.isnull().sum())

Shape after cleaning: (18631, 3)

Label distribution:
label
0    11322
1     7309
Name: count, dtype: int64

Missing values:
Email Text    0
Email Type    0
label         0
dtype: int64

In [13]:
print("Total emails:", len(df))
print("Duplicate emails:", df["Email Text"].duplicated().sum())

Total emails: 18631
Duplicate emails: 1117

In [14]:
df = df.drop_duplicates(subset=["Email Text"]).reset_index(drop=True)

print("After removing duplicates:", len(df))

After removing duplicates: 17514

In [15]:
print(df.head())

print("\nFinal shape:", df.shape)

print("\nFinal label distribution:")
print(df["label"].value_counts())

print("\nFinal percentages:")
print(df["label"].value_counts(normalize=True) * 100)

                                          Email Text      Email Type  label
0  re : 6 . 1100 , disc : uniformitarianism , re ...      Safe Email      0
1  the other side of * galicismos * * galicismo *...      Safe Email      0
2  re : equistar deal tickets are you still avail...      Safe Email      0
3  Hello I am your hot lil horny toy. I am the on...  Phishing Email      1
4  software at incredibly low prices ( 86 % lower...  Phishing Email      1

Final shape: (17514, 3)

Final label distribution:
label
0    10977
1     6537
Name: count, dtype: int64

Final percentages:
label
0    62.675574
1    37.324426
Name: proportion, dtype: float64

In [16]:
from sklearn.model_selection import train_test_split

# First split: 80% training, 20% temporary
train_df, temp_df = train_test_split(
    df,
    test_size=0.20,
    stratify=df["label"],
    random_state=42
)

# Second split: divide the remaining 20% equally
# → 10% validation + 10% test
val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["label"],
    random_state=42
)

print("TRAIN:", len(train_df))
print("VALIDATION:", len(val_df))
print("TEST:", len(test_df))

TRAIN: 14011
VALIDATION: 1751
TEST: 1752

In [17]:
print("\nTRAIN distribution:")
print(train_df["label"].value_counts())

print("\nVALIDATION distribution:")
print(val_df["label"].value_counts())

print("\nTEST distribution:")
print(test_df["label"].value_counts())

TRAIN distribution:
label
0    8781
1    5230
Name: count, dtype: int64

VALIDATION distribution:
label
0    1098
1     653
Name: count, dtype: int64

TEST distribution:
label
0    1098
1     654
Name: count, dtype: int64

In [18]:
train_texts = set(train_df["Email Text"])
val_texts = set(val_df["Email Text"])
test_texts = set(test_df["Email Text"])

print("Train ∩ Validation:", len(train_texts & val_texts))
print("Train ∩ Test:", len(train_texts & test_texts))
print("Validation ∩ Test:", len(val_texts & test_texts))

Train ∩ Validation: 0
Train ∩ Test: 0
Validation ∩ Test: 0

In [19]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

MODEL_NAME = "distilbert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2,
    id2label={
        0: "LEGITIMATE",
        1: "PHISHING"
    },
    label2id={
        "LEGITIMATE": 0,
        "PHISHING": 1
    }
)

print("Model loaded successfully!")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Model loaded successfully!

In [20]:
print(model)

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [21]:
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(
    p.numel() for p in model.parameters()
    if p.requires_grad
)

print("Total parameters:", f"{total_params:,}")
print("Trainable parameters:", f"{trainable_params:,}")

Total parameters: 66,955,010
Trainable parameters: 66,955,010

In [22]:
import torch

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

model.to(device)

print("Using device:", device)

Using device: cuda

In [23]:
from datasets import Dataset

train_dataset = Dataset.from_pandas(
    train_df[["Email Text", "label"]],
    preserve_index=False
)

val_dataset = Dataset.from_pandas(
    val_df[["Email Text", "label"]],
    preserve_index=False
)

test_dataset = Dataset.from_pandas(
    test_df[["Email Text", "label"]],
    preserve_index=False
)

print(train_dataset)
print(val_dataset)
print(test_dataset)

Dataset({
    features: ['Email Text', 'label'],
    num_rows: 14011
})
Dataset({
    features: ['Email Text', 'label'],
    num_rows: 1751
})
Dataset({
    features: ['Email Text', 'label'],
    num_rows: 1752
})

In [24]:
MAX_LENGTH = 512

def tokenize_function(batch):
    return tokenizer(
        batch["Email Text"],
        truncation=True,
        max_length=MAX_LENGTH
    )

train_tokenized = train_dataset.map(
    tokenize_function,
    batched=True,
    remove_columns=["Email Text"]
)

val_tokenized = val_dataset.map(
    tokenize_function,
    batched=True,
    remove_columns=["Email Text"]
)

test_tokenized = test_dataset.map(
    tokenize_function,
    batched=True,
    remove_columns=["Email Text"]
)

print(train_tokenized)

Map:   0%|          | 0/14011 [00:00<?, ? examples/s]

Map:   0%|          | 0/1751 [00:00<?, ? examples/s]

Map:   0%|          | 0/1752 [00:00<?, ? examples/s]

Dataset({
    features: ['label', 'input_ids', 'attention_mask'],
    num_rows: 14011
})

In [25]:
print(train_tokenized[0])

{'label': 0, 'input_ids': [101, 20604, 20231, 1998, 19476, 2655, 2005, 4981, 3034, 1024, 1996, 20231, 1997, 20604, 4155, 1006, 2238, 2656, 1011, 2676, 1007, 8395, 1024, 1996, 19476, 1997, 20604, 4155, 1006, 2238, 2603, 1007, 2044, 1037, 2200, 3144, 2034, 20604, 20231, 3034, 2012, 15529, 2378, 2089, 2687, 1010, 1996, 2533, 1997, 15397, 2012, 1996, 2118, 1997, 4307, 2012, 27929, 1011, 28843, 18675, 29474, 2005, 1996, 2117, 20604, 20231, 3034, 2000, 2022, 2218, 2238, 2656, 1011, 2676, 1010, 2639, 1012, 1996, 3034, 2097, 2022, 11677, 2011, 1037, 8395, 2239, 20604, 19476, 2000, 2022, 2218, 2238, 2603, 1010, 2639, 1012, 2119, 2824, 2097, 2202, 2173, 2076, 1996, 12158, 2554, 1997, 2637, 2621, 2820, 1006, 2238, 17465, 1011, 2251, 2382, 1007, 2029, 2097, 2022, 2218, 2012, 1996, 2118, 1997, 4307, 2012, 27929, 1011, 28843, 1006, 4037, 1024, 8299, 1024, 1013, 1013, 7479, 1012, 10272, 2386, 1012, 21318, 14194, 1012, 3968, 2226, 1013, 17002, 7076, 2102, 1007, 1012, 6818, 2097, 2022, 3479, 2006, 1996, 3978, 1997, 5330, 2094, 10812, 29474, 1010, 2000, 2022, 13224, 2011, 1037, 4989, 2837, 1012, 2169, 2831, 2097, 2022, 2871, 2781, 2146, 2007, 2019, 3176, 16068, 2781, 2005, 6594, 1012, 3531, 4604, 2184, 4809, 1997, 2019, 10812, 10061, 1010, 2012, 2087, 1016, 1011, 5530, 2146, 1006, 2164, 4973, 1998, 7604, 1007, 1012, 3531, 4372, 20464, 9232, 1037, 1017, 2595, 2629, 4003, 2007, 6342, 25526, 14643, 3258, 5517, 2171, 1997, 3259, 1010, 2171, 1997, 3166, 1010, 12912, 1998, 4769, 1010, 2164, 1041, 1011, 5653, 4769, 1010, 3042, 2193, 1010, 1998, 5769, 4415, 3251, 1996, 23298, 2003, 2005, 1996, 3034, 2030, 1996, 8395, 1012, 1996, 2171, 1997, 1996, 3166, 5807, 4140, 3711, 2006, 1996, 10061, 1012, 27842, 2011, 1041, 1011, 5653, 2030, 6904, 2595, 2097, 2025, 2022, 3970, 1012, 29474, 2323, 2022, 2695, 10665, 2098, 2053, 2101, 2084, 2233, 2321, 1010, 2639, 1010, 1998, 2741, 2000, 1024, 17532, 3841, 2863, 5302, 4609, 1012, 2533, 1997, 15397, 1010, 2871, 2620, 2620, 13109, 2497, 1012, 2118, 1997, 4307, 2012, 27929, 1011, 28843, 1012, 27929, 1010, 6335, 6079, 17914, 2487, 10383, 3034, 4037, 1024, 8299, 1024, 1013, 1013, 7479, 1012, 10272, 2386, 1012, 21318, 14194, 1012, 3968, 2226, 1013, 2967, 1013, 20116, 1013, 17002, 7076, 2102, 1013, 9281, 1013, 20604, 1012, 16129, 3531, 4638, 2041, 1996, 20604, 15397, 8264, 2073, 19106, 4981, 2006, 20604, 4155, 2064, 2022, 6866, 1998, 22817, 1012, 1996, 4769, 2003, 1024, 8299, 1024, 1013, 1013, 7479, 1012, 15529, 1012, 3968, 2226, 1013, 29466, 1013, 5869, 1013, 15397, 1013, 20604, 1013, 3531, 3622, 2035, 27050, 2055, 1996, 3034, 1998, 8395, 2000, 1024, 17532, 3841, 2863, 5302, 4609, 10373, 1024, 1041, 1011, 3841, 2863, 1030, 21318, 14194, 1012, 3968, 2226, 10093, 1024, 1006, 20335, 1007, 21211, 1011, 6390, 24594, 6904, 2595, 1024, 1006, 19883, 1007, 21211, 1011, 4090, 28756, 10863, 2837, 3312, 20118, 4609, 1006, 15529, 1007, 17532, 3841, 2863, 5302, 4609, 1006, 21318, 14194, 1007, 5292, 23806, 8501, 2099, 1006, 15529, 1007, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [26]:
lengths = [
    len(x["input_ids"])
    for x in train_tokenized.select(range(min(1000, len(train_tokenized))))
]

print("Shortest:", min(lengths))
print("Longest:", max(lengths))
print("Average:", sum(lengths) / len(lengths))

Shortest: 3
Longest: 512
Average: 274.738

In [27]:
MAX_LENGTH = 512
STRIDE = 128

def tokenize_with_chunks(batch):
    return tokenizer(
        batch["Email Text"],
        truncation=True,
        max_length=MAX_LENGTH,
        stride=STRIDE,
        return_overflowing_tokens=True,
        padding=False
    )

In [28]:
# Find the longest email based on token count
token_lengths = []

for text in df["Email Text"]:
    tokens = tokenizer(
        text,
        truncation=False,
        add_special_tokens=True
    )["input_ids"]
    token_lengths.append(len(tokens))

df["token_length"] = token_lengths

print("Longest email:", df["token_length"].max(), "tokens")

long_email = df.loc[df["token_length"].idxmax(), "Email Text"]

print("\nCharacters:", len(long_email))
print("First 500 characters:\n")
print(long_email[:500])

Token indices sequence length is longer than the specified maximum sequence length for this model (616 > 512). Running this sequence through the model will result in indexing errors

Longest email: 4132149 tokens

Characters: 17036692
First 500 characters:

0,"Subject: great part-time or summer job ! * * * * * * * * * * * * * * * we have display boxes with credit applications that we need to place in the small owner-operated stores in your area . here is what you do : 1 . introduce yourself to the store owner or manager . 2 . use our 90 % effective script which tells them how this little display box will save their customers hundreds of dollars , be a drawing card for their business , and make them from $ 5 . 00 to $ 15 . 00 or more for every app s

In [29]:
long_email_chunks = tokenizer(
    long_email,
    truncation=True,
    max_length=MAX_LENGTH,
    stride=STRIDE,
    return_overflowing_tokens=True,
    padding=False
)

print("Original token count:",
      len(tokenizer(long_email, truncation=False)["input_ids"]))

print("Number of chunks:",
      len(long_email_chunks["input_ids"]))

print("\nChunk lengths:")

for i, chunk in enumerate(long_email_chunks["input_ids"]):
    print(f"Chunk {i + 1}: {len(chunk)} tokens")

Original token count: 4132149
Number of chunks: 10817

Chunk lengths:
Chunk 1: 512 tokens
Chunk 2: 512 tokens
Chunk 3: 512 tokens
Chunk 4: 512 tokens
Chunk 5: 512 tokens
Chunk 6: 512 tokens
Chunk 7: 512 tokens
Chunk 8: 512 tokens
Chunk 9: 512 tokens
Chunk 10: 512 tokens
Chunk 11: 512 tokens
Chunk 12: 512 tokens
Chunk 13: 512 tokens
Chunk 14: 512 tokens
Chunk 15: 512 tokens
Chunk 16: 512 tokens
Chunk 17: 512 tokens
Chunk 18: 512 tokens
Chunk 19: 512 tokens
Chunk 20: 512 tokens
Chunk 21: 512 tokens
Chunk 22: 512 tokens
Chunk 23: 512 tokens
Chunk 24: 512 tokens
Chunk 25: 512 tokens
Chunk 26: 512 tokens
Chunk 27: 512 tokens
Chunk 28: 512 tokens
Chunk 29: 512 tokens
Chunk 30: 512 tokens
Chunk 31: 512 tokens
Chunk 32: 512 tokens
Chunk 33: 512 tokens
Chunk 34: 512 tokens
Chunk 35: 512 tokens
Chunk 36: 512 tokens
Chunk 37: 512 tokens
Chunk 38: 512 tokens
Chunk 39: 512 tokens
Chunk 40: 512 tokens
Chunk 41: 512 tokens
Chunk 42: 512 tokens
Chunk 43: 512 tokens
Chunk 44: 512 tokens
Chunk 45: 512 tokens
Chunk 46: 512 tokens
Chunk 47: 512 tokens
Chunk 48: 512 tokens
Chunk 49: 512 tokens
Chunk 50: 512 tokens
Chunk 51: 512 tokens
Chunk 52: 512 tokens
Chunk 53: 512 tokens
Chunk 54: 512 tokens
Chunk 55: 512 tokens
Chunk 56: 512 tokens
Chunk 57: 512 tokens
Chunk 58: 512 tokens
Chunk 59: 512 tokens
Chunk 60: 512 tokens
Chunk 61: 512 tokens
Chunk 62: 512 tokens
Chunk 63: 512 tokens
Chunk 64: 512 tokens
Chunk 65: 512 tokens
Chunk 66: 512 tokens
Chunk 67: 512 tokens
Chunk 68: 512 tokens
Chunk 69: 512 tokens
Chunk 70: 512 tokens
Chunk 71: 512 tokens
Chunk 72: 512 tokens
Chunk 73: 512 tokens
Chunk 74: 512 tokens
Chunk 75: 512 tokens
Chunk 76: 512 tokens
Chunk 77: 512 tokens
Chunk 78: 512 tokens
Chunk 79: 512 tokens
Chunk 80: 512 tokens
Chunk 81: 512 tokens
Chunk 82: 512 tokens
Chunk 83: 512 tokens
Chunk 84: 512 tokens
Chunk 85: 512 tokens
Chunk 86: 512 tokens
Chunk 87: 512 tokens
Chunk 88: 512 tokens
Chunk 89: 512 tokens
Chunk 90: 512 tokens
Chunk 91: 512 tokens
Chunk 92: 512 tokens
Chunk 93: 512 tokens
Chunk 94: 512 tokens
Chunk 95: 512 tokens
Chunk 96: 512 tokens
Chunk 97: 512 tokens
Chunk 98: 512 tokens
Chunk 99: 512 tokens
Chunk 100: 512 tokens
Chunk 101: 512 tokens
Chunk 102: 512 tokens
Chunk 103: 512 tokens
Chunk 104: 512 tokens
Chunk 105: 512 tokens
Chunk 106: 512 tokens
Chunk 107: 512 tokens
Chunk 108: 512 tokens
Chunk 109: 512 tokens
Chunk 110: 512 tokens
Chunk 111: 512 tokens
Chunk 112: 512 tokens
Chunk 113: 512 tokens
Chunk 114: 512 tokens
Chunk 115: 512 tokens
Chunk 116: 512 tokens
Chunk 117: 512 tokens
Chunk 118: 512 tokens
Chunk 119: 512 tokens
Chunk 120: 512 tokens
Chunk 121: 512 tokens
Chunk 122: 512 tokens
Chunk 123: 512 tokens
Chunk 124: 512 tokens
Chunk 125: 512 tokens
Chunk 126: 512 tokens
Chunk 127: 512 tokens
Chunk 128: 512 tokens
Chunk 129: 512 tokens
Chunk 130: 512 tokens
Chunk 131: 512 tokens
Chunk 132: 512 tokens
Chunk 133: 512 tokens
Chunk 134: 512 tokens
Chunk 135: 512 tokens
Chunk 136: 512 tokens
Chunk 137: 512 tokens
Chunk 138: 512 tokens
Chunk 139: 512 tokens
Chunk 140: 512 tokens
Chunk 141: 512 tokens
Chunk 142: 512 tokens
Chunk 143: 512 tokens
Chunk 144: 512 tokens
Chunk 145: 512 tokens
Chunk 146: 512 tokens
Chunk 147: 512 tokens
Chunk 148: 512 tokens
Chunk 149: 512 tokens
Chunk 150: 512 tokens
Chunk 151: 512 tokens
Chunk 152: 512 tokens
Chunk 153: 512 tokens
Chunk 154: 512 tokens
Chunk 155: 512 tokens
Chunk 156: 512 tokens
Chunk 157: 512 tokens
Chunk 158: 512 tokens
Chunk 159: 512 tokens
Chunk 160: 512 tokens
Chunk 161: 512 tokens
Chunk 162: 512 tokens
Chunk 163: 512 tokens
Chunk 164: 512 tokens
Chunk 165: 512 tokens
Chunk 166: 512 tokens
Chunk 167: 512 tokens
Chunk 168: 512 tokens
Chunk 169: 512 tokens
Chunk 170: 512 tokens
Chunk 171: 512 tokens
Chunk 172: 512 tokens
Chunk 173: 512 tokens
Chunk 174: 512 tokens
Chunk 175: 512 tokens
Chunk 176: 512 tokens
Chunk 177: 512 tokens
Chunk 178: 512 tokens
Chunk 179: 512 tokens
Chunk 180: 512 tokens
Chunk 181: 512 tokens
Chunk 182: 512 tokens
Chunk 183: 512 tokens
Chunk 184: 512 tokens
Chunk 185: 512 tokens
Chunk 186: 512 tokens
Chunk 187: 512 tokens
Chunk 188: 512 tokens
Chunk 189: 512 tokens
Chunk 190: 512 tokens
Chunk 191: 512 tokens
Chunk 192: 512 tokens
Chunk 193: 512 tokens
Chunk 194: 512 tokens
Chunk 195: 512 tokens
Chunk 196: 512 tokens
Chunk 197: 512 tokens
Chunk 198: 512 tokens
Chunk 199: 512 tokens
Chunk 200: 512 tokens
Chunk 201: 512 tokens
Chunk 202: 512 tokens
Chunk 203: 512 tokens
Chunk 204: 512 tokens
Chunk 205: 512 tokens
Chunk 206: 512 tokens
Chunk 207: 512 tokens
Chunk 208: 512 tokens
Chunk 209: 512 tokens
Chunk 210: 512 tokens
Chunk 211: 512 tokens
Chunk 212: 512 tokens
Chunk 213: 512 tokens
Chunk 214: 512 tokens
Chunk 215: 512 tokens
Chunk 216: 512 tokens
Chunk 217: 512 tokens
Chunk 218: 512 tokens
Chunk 219: 512 tokens
Chunk 220: 512 tokens
Chunk 221: 512 tokens
Chunk 222: 512 tokens
Chunk 223: 512 tokens
Chunk 224: 512 tokens
Chunk 225: 512 tokens
Chunk 226: 512 tokens
Chunk 227: 512 tokens
Chunk 228: 512 tokens
Chunk 229: 512 tokens
Chunk 230: 512 tokens
Chunk 231: 512 tokens
Chunk 232: 512 tokens
Chunk 233: 512 tokens
Chunk 234: 512 tokens
Chunk 235: 512 tokens
Chunk 236: 512 tokens
Chunk 237: 512 tokens
Chunk 238: 512 tokens
Chunk 239: 512 tokens
Chunk 240: 512 tokens
Chunk 241: 512 tokens
Chunk 242: 512 tokens
Chunk 243: 512 tokens
Chunk 244: 512 tokens
Chunk 245: 512 tokens
Chunk 246: 512 tokens
Chunk 247: 512 tokens
Chunk 248: 512 tokens
Chunk 249: 512 tokens
Chunk 250: 512 tokens
Chunk 251: 512 tokens
Chunk 252: 512 tokens
Chunk 253: 512 tokens
Chunk 254: 512 tokens
Chunk 255: 512 tokens
Chunk 256: 512 tokens
Chunk 257: 512 tokens
Chunk 258: 512 tokens
Chunk 259: 512 tokens
Chunk 260: 512 tokens
Chunk 261: 512 tokens
Chunk 262: 512 tokens
Chunk 263: 512 tokens
Chunk 264: 512 tokens
Chunk 265: 512 tokens
Chunk 266: 512 tokens
Chunk 267: 512 tokens
Chunk 268: 512 tokens
Chunk 269: 512 tokens
Chunk 270: 512 tokens
Chunk 271: 512 tokens
Chunk 272: 512 tokens
Chunk 273: 512 tokens
Chunk 274: 512 tokens
Chunk 275: 512 tokens
Chunk 276: 512 tokens
Chunk 277: 512 tokens
Chunk 278: 512 tokens
Chunk 279: 512 tokens
Chunk 280: 512 tokens
Chunk 281: 512 tokens
Chunk 282: 512 tokens
Chunk 283: 512 tokens
Chunk 284: 512 tokens
Chunk 285: 512 tokens
Chunk 286: 512 tokens
Chunk 287: 512 tokens
Chunk 288: 512 tokens
Chunk 289: 512 tokens
Chunk 290: 512 tokens
Chunk 291: 512 tokens
Chunk 292: 512 tokens
Chunk 293: 512 tokens
Chunk 294: 512 tokens
Chunk 295: 512 tokens
Chunk 296: 512 tokens
Chunk 297: 512 tokens
Chunk 298: 512 tokens
Chunk 299: 512 tokens
Chunk 300: 512 tokens
Chunk 301: 512 tokens
Chunk 302: 512 tokens
Chunk 303: 512 tokens
Chunk 304: 512 tokens
Chunk 305: 512 tokens
Chunk 306: 512 tokens
Chunk 307: 512 tokens
Chunk 308: 512 tokens
Chunk 309: 512 tokens
Chunk 310: 512 tokens
Chunk 311: 512 tokens
Chunk 312: 512 tokens
Chunk 313: 512 tokens
Chunk 314: 512 tokens
Chunk 315: 512 tokens
Chunk 316: 512 tokens
Chunk 317: 512 tokens
Chunk 318: 512 tokens
Chunk 319: 512 tokens
Chunk 320: 512 tokens
Chunk 321: 512 tokens
Chunk 322: 512 tokens
Chunk 323: 512 tokens
Chunk 324: 512 tokens
Chunk 325: 512 tokens
Chunk 326: 512 tokens
Chunk 327: 512 tokens
Chunk 328: 512 tokens
Chunk 329: 512 tokens
Chunk 330: 512 tokens
Chunk 331: 512 tokens
Chunk 332: 512 tokens
Chunk 333: 512 tokens
Chunk 334: 512 tokens
Chunk 335: 512 tokens
Chunk 336: 512 tokens
Chunk 337: 512 tokens
Chunk 338: 512 tokens
Chunk 339: 512 tokens
Chunk 340: 512 tokens
Chunk 341: 512 tokens
Chunk 342: 512 tokens
Chunk 343: 512 tokens
Chunk 344: 512 tokens
Chunk 345: 512 tokens
Chunk 346: 512 tokens
Chunk 347: 512 tokens
Chunk 348: 512 tokens
Chunk 349: 512 tokens
Chunk 350: 512 tokens
Chunk 351: 512 tokens
Chunk 352: 512 tokens
Chunk 353: 512 tokens
Chunk 354: 512 tokens
Chunk 355: 512 tokens
Chunk 356: 512 tokens
Chunk 357: 512 tokens
Chunk 358: 512 tokens
Chunk 359: 512 tokens
Chunk 360: 512 tokens
Chunk 361: 512 tokens
Chunk 362: 512 tokens
Chunk 363: 512 tokens
Chunk 364: 512 tokens
Chunk 365: 512 tokens
Chunk 366: 512 tokens
Chunk 367: 512 tokens
Chunk 368: 512 tokens
Chunk 369: 512 tokens
Chunk 370: 512 tokens
Chunk 371: 512 tokens
Chunk 372: 512 tokens
Chunk 373: 512 tokens
Chunk 374: 512 tokens
Chunk 375: 512 tokens
Chunk 376: 512 tokens
Chunk 377: 512 tokens
Chunk 378: 512 tokens
Chunk 379: 512 tokens
Chunk 380: 512 tokens
Chunk 381: 512 tokens
Chunk 382: 512 tokens
Chunk 383: 512 tokens
Chunk 384: 512 tokens
Chunk 385: 512 tokens
Chunk 386: 512 tokens
Chunk 387: 512 tokens
Chunk 388: 512 tokens
Chunk 389: 512 tokens
Chunk 390: 512 tokens
Chunk 391: 512 tokens
Chunk 392: 512 tokens
Chunk 393: 512 tokens
Chunk 394: 512 tokens
Chunk 395: 512 tokens
Chunk 396: 512 tokens
Chunk 397: 512 tokens
Chunk 398: 512 tokens
Chunk 399: 512 tokens
Chunk 400: 512 tokens
Chunk 401: 512 tokens
Chunk 402: 512 tokens
Chunk 403: 512 tokens
Chunk 404: 512 tokens
Chunk 405: 512 tokens
Chunk 406: 512 tokens
Chunk 407: 512 tokens
Chunk 408: 512 tokens
Chunk 409: 512 tokens
Chunk 410: 512 tokens
Chunk 411: 512 tokens
Chunk 412: 512 tokens
Chunk 413: 512 tokens
Chunk 414: 512 tokens
Chunk 415: 512 tokens
Chunk 416: 512 tokens
Chunk 417: 512 tokens
Chunk 418: 512 tokens
Chunk 419: 512 tokens
Chunk 420: 512 tokens
Chunk 421: 512 tokens
Chunk 422: 512 tokens
Chunk 423: 512 tokens
Chunk 424: 512 tokens
Chunk 425: 512 tokens
Chunk 426: 512 tokens
Chunk 427: 512 tokens
Chunk 428: 512 tokens
Chunk 429: 512 tokens
Chunk 430: 512 tokens
Chunk 431: 512 tokens
Chunk 432: 512 tokens
Chunk 433: 512 tokens
Chunk 434: 512 tokens
Chunk 435: 512 tokens
Chunk 436: 512 tokens
Chunk 437: 512 tokens
Chunk 438: 512 tokens
Chunk 439: 512 tokens
Chunk 440: 512 tokens
Chunk 441: 512 tokens
Chunk 442: 512 tokens
Chunk 443: 512 tokens
Chunk 444: 512 tokens
Chunk 445: 512 tokens
Chunk 446: 512 tokens
Chunk 447: 512 tokens
Chunk 448: 512 tokens
Chunk 449: 512 tokens
Chunk 450: 512 tokens
Chunk 451: 512 tokens
Chunk 452: 512 tokens
Chunk 453: 512 tokens
Chunk 454: 512 tokens
Chunk 455: 512 tokens
Chunk 456: 512 tokens
Chunk 457: 512 tokens
Chunk 458: 512 tokens
Chunk 459: 512 tokens
Chunk 460: 512 tokens
Chunk 461: 512 tokens
Chunk 462: 512 tokens
Chunk 463: 512 tokens
Chunk 464: 512 tokens
Chunk 465: 512 tokens
Chunk 466: 512 tokens
Chunk 467: 512 tokens
Chunk 468: 512 tokens
Chunk 469: 512 tokens
Chunk 470: 512 tokens
Chunk 471: 512 tokens
Chunk 472: 512 tokens
Chunk 473: 512 tokens
Chunk 474: 512 tokens
Chunk 475: 512 tokens
Chunk 476: 512 tokens
Chunk 477: 512 tokens
Chunk 478: 512 tokens
Chunk 479: 512 tokens
Chunk 480: 512 tokens
Chunk 481: 512 tokens
Chunk 482: 512 tokens
Chunk 483: 512 tokens
Chunk 484: 512 tokens
Chunk 485: 512 tokens
Chunk 486: 512 tokens
Chunk 487: 512 tokens
Chunk 488: 512 tokens
Chunk 489: 512 tokens
Chunk 490: 512 tokens
Chunk 491: 512 tokens
Chunk 492: 512 tokens
Chunk 493: 512 tokens
Chunk 494: 512 tokens
Chunk 495: 512 tokens
Chunk 496: 512 tokens
Chunk 497: 512 tokens
Chunk 498: 512 tokens
Chunk 499: 512 tokens
Chunk 500: 512 tokens
Chunk 501: 512 tokens
Chunk 502: 512 tokens
Chunk 503: 512 tokens
Chunk 504: 512 tokens
Chunk 505: 512 tokens
Chunk 506: 512 tokens
Chunk 507: 512 tokens
Chunk 508: 512 tokens
Chunk 509: 512 tokens
Chunk 510: 512 tokens
Chunk 511: 512 tokens
Chunk 512: 512 tokens
Chunk 513: 512 tokens
Chunk 514: 512 tokens
Chunk 515: 512 tokens
Chunk 516: 512 tokens
Chunk 517: 512 tokens
Chunk 518: 512 tokens
Chunk 519: 512 tokens
Chunk 520: 512 tokens
Chunk 521: 512 tokens
Chunk 522: 512 tokens
Chunk 523: 512 tokens
Chunk 524: 512 tokens
Chunk 525: 512 tokens
Chunk 526: 512 tokens
Chunk 527: 512 tokens
Chunk 528: 512 tokens
Chunk 529: 512 tokens
Chunk 530: 512 tokens
Chunk 531: 512 tokens
Chunk 532: 512 tokens
Chunk 533: 512 tokens
Chunk 534: 512 tokens
Chunk 535: 512 tokens
Chunk 536: 512 tokens
Chunk 537: 512 tokens
Chunk 538: 512 tokens
Chunk 539: 512 tokens
Chunk 540: 512 tokens
Chunk 541: 512 tokens
Chunk 542: 512 tokens
Chunk 543: 512 tokens
Chunk 544: 512 tokens
Chunk 545: 512 tokens
Chunk 546: 512 tokens
Chunk 547: 512 tokens
Chunk 548: 512 tokens
Chunk 549: 512 tokens
Chunk 550: 512 tokens
Chunk 551: 512 tokens
Chunk 552: 512 tokens
Chunk 553: 512 tokens
Chunk 554: 512 tokens
Chunk 555: 512 tokens
Chunk 556: 512 tokens
Chunk 557: 512 tokens
Chunk 558: 512 tokens
Chunk 559: 512 tokens
Chunk 560: 512 tokens
Chunk 561: 512 tokens
Chunk 562: 512 tokens
Chunk 563: 512 tokens
Chunk 564: 512 tokens
Chunk 565: 512 tokens
Chunk 566: 512 tokens
Chunk 567: 512 tokens
Chunk 568: 512 tokens
Chunk 569: 512 tokens
Chunk 570: 512 tokens
Chunk 571: 512 tokens
Chunk 572: 512 tokens
Chunk 573: 512 tokens
Chunk 574: 512 tokens
Chunk 575: 512 tokens
Chunk 576: 512 tokens
Chunk 577: 512 tokens
Chunk 578: 512 tokens
Chunk 579: 512 tokens
Chunk 580: 512 tokens
Chunk 581: 512 tokens
Chunk 582: 512 tokens
Chunk 583: 512 tokens
Chunk 584: 512 tokens
Chunk 585: 512 tokens
Chunk 586: 512 tokens
Chunk 587: 512 tokens
Chunk 588: 512 tokens
Chunk 589: 512 tokens
Chunk 590: 512 tokens
Chunk 591: 512 tokens
Chunk 592: 512 tokens
Chunk 593: 512 tokens
Chunk 594: 512 tokens
Chunk 595: 512 tokens
Chunk 596: 512 tokens
Chunk 597: 512 tokens
Chunk 598: 512 tokens
Chunk 599: 512 tokens
Chunk 600: 512 tokens
Chunk 601: 512 tokens
Chunk 602: 512 tokens
Chunk 603: 512 tokens
Chunk 604: 512 tokens
Chunk 605: 512 tokens
Chunk 606: 512 tokens
Chunk 607: 512 tokens
Chunk 608: 512 tokens
Chunk 609: 512 tokens
Chunk 610: 512 tokens
Chunk 611: 512 tokens
Chunk 612: 512 tokens
Chunk 613: 512 tokens
Chunk 614: 512 tokens
Chunk 615: 512 tokens
Chunk 616: 512 tokens
Chunk 617: 512 tokens
Chunk 618: 512 tokens
Chunk 619: 512 tokens
Chunk 620: 512 tokens
Chunk 621: 512 tokens
Chunk 622: 512 tokens
Chunk 623: 512 tokens
Chunk 624: 512 tokens
Chunk 625: 512 tokens
Chunk 626: 512 tokens
Chunk 627: 512 tokens
Chunk 628: 512 tokens
Chunk 629: 512 tokens
Chunk 630: 512 tokens
Chunk 631: 512 tokens
Chunk 632: 512 tokens
Chunk 633: 512 tokens
Chunk 634: 512 tokens
Chunk 635: 512 tokens
Chunk 636: 512 tokens
Chunk 637: 512 tokens
Chunk 638: 512 tokens
Chunk 639: 512 tokens
Chunk 640: 512 tokens
Chunk 641: 512 tokens
Chunk 642: 512 tokens
Chunk 643: 512 tokens
Chunk 644: 512 tokens
Chunk 645: 512 tokens
Chunk 646: 512 tokens
Chunk 647: 512 tokens
Chunk 648: 512 tokens
Chunk 649: 512 tokens
Chunk 650: 512 tokens
Chunk 651: 512 tokens
Chunk 652: 512 tokens
Chunk 653: 512 tokens
Chunk 654: 512 tokens
Chunk 655: 512 tokens
Chunk 656: 512 tokens
Chunk 657: 512 tokens
Chunk 658: 512 tokens
Chunk 659: 512 tokens
Chunk 660: 512 tokens
Chunk 661: 512 tokens
Chunk 662: 512 tokens
Chunk 663: 512 tokens
Chunk 664: 512 tokens
Chunk 665: 512 tokens
Chunk 666: 512 tokens
Chunk 667: 512 tokens
Chunk 668: 512 tokens
Chunk 669: 512 tokens
Chunk 670: 512 tokens
Chunk 671: 512 tokens
Chunk 672: 512 tokens
Chunk 673: 512 tokens
Chunk 674: 512 tokens
Chunk 675: 512 tokens
Chunk 676: 512 tokens
Chunk 677: 512 tokens
Chunk 678: 512 tokens
Chunk 679: 512 tokens
Chunk 680: 512 tokens
Chunk 681: 512 tokens
Chunk 682: 512 tokens
Chunk 683: 512 tokens
Chunk 684: 512 tokens
Chunk 685: 512 tokens
Chunk 686: 512 tokens
Chunk 687: 512 tokens
Chunk 688: 512 tokens
Chunk 689: 512 tokens
Chunk 690: 512 tokens
Chunk 691: 512 tokens
Chunk 692: 512 tokens
Chunk 693: 512 tokens
Chunk 694: 512 tokens
Chunk 695: 512 tokens
Chunk 696: 512 tokens
Chunk 697: 512 tokens
Chunk 698: 512 tokens
Chunk 699: 512 tokens
Chunk 700: 512 tokens
Chunk 701: 512 tokens
Chunk 702: 512 tokens
Chunk 703: 512 tokens
Chunk 704: 512 tokens
Chunk 705: 512 tokens
Chunk 706: 512 tokens
Chunk 707: 512 tokens
Chunk 708: 512 tokens
Chunk 709: 512 tokens
Chunk 710: 512 tokens
Chunk 711: 512 tokens
Chunk 712: 512 tokens
Chunk 713: 512 tokens
Chunk 714: 512 tokens
Chunk 715: 512 tokens
Chunk 716: 512 tokens
Chunk 717: 512 tokens
Chunk 718: 512 tokens
Chunk 719: 512 tokens
Chunk 720: 512 tokens
Chunk 721: 512 tokens
Chunk 722: 512 tokens
Chunk 723: 512 tokens
Chunk 724: 512 tokens
Chunk 725: 512 tokens
Chunk 726: 512 tokens
Chunk 727: 512 tokens
Chunk 728: 512 tokens
Chunk 729: 512 tokens
Chunk 730: 512 tokens
Chunk 731: 512 tokens
Chunk 732: 512 tokens
Chunk 733: 512 tokens
Chunk 734: 512 tokens
Chunk 735: 512 tokens
Chunk 736: 512 tokens
Chunk 737: 512 tokens
Chunk 738: 512 tokens
Chunk 739: 512 tokens
Chunk 740: 512 tokens
Chunk 741: 512 tokens
Chunk 742: 512 tokens
Chunk 743: 512 tokens
Chunk 744: 512 tokens
Chunk 745: 512 tokens
Chunk 746: 512 tokens
Chunk 747: 512 tokens
Chunk 748: 512 tokens
Chunk 749: 512 tokens
Chunk 750: 512 tokens
Chunk 751: 512 tokens
Chunk 752: 512 tokens
Chunk 753: 512 tokens
Chunk 754: 512 tokens
Chunk 755: 512 tokens
Chunk 756: 512 tokens
Chunk 757: 512 tokens
Chunk 758: 512 tokens
Chunk 759: 512 tokens
Chunk 760: 512 tokens
Chunk 761: 512 tokens
Chunk 762: 512 tokens
Chunk 763: 512 tokens
Chunk 764: 512 tokens
Chunk 765: 512 tokens
Chunk 766: 512 tokens
Chunk 767: 512 tokens
Chunk 768: 512 tokens
Chunk 769: 512 tokens
Chunk 770: 512 tokens
Chunk 771: 512 tokens
Chunk 772: 512 tokens
Chunk 773: 512 tokens
Chunk 774: 512 tokens
Chunk 775: 512 tokens
Chunk 776: 512 tokens
Chunk 777: 512 tokens
Chunk 778: 512 tokens
Chunk 779: 512 tokens
Chunk 780: 512 tokens
Chunk 781: 512 tokens
Chunk 782: 512 tokens
Chunk 783: 512 tokens
Chunk 784: 512 tokens
Chunk 785: 512 tokens
Chunk 786: 512 tokens
Chunk 787: 512 tokens
Chunk 788: 512 tokens
Chunk 789: 512 tokens
Chunk 790: 512 tokens
Chunk 791: 512 tokens
Chunk 792: 512 tokens
Chunk 793: 512 tokens
Chunk 794: 512 tokens
Chunk 795: 512 tokens
Chunk 796: 512 tokens
Chunk 797: 512 tokens
Chunk 798: 512 tokens
Chunk 799: 512 tokens
Chunk 800: 512 tokens
Chunk 801: 512 tokens
Chunk 802: 512 tokens
Chunk 803: 512 tokens
Chunk 804: 512 tokens
Chunk 805: 512 tokens
Chunk 806: 512 tokens
Chunk 807: 512 tokens
Chunk 808: 512 tokens
Chunk 809: 512 tokens
Chunk 810: 512 tokens
Chunk 811: 512 tokens
Chunk 812: 512 tokens
Chunk 813: 512 tokens
Chunk 814: 512 tokens
Chunk 815: 512 tokens
Chunk 816: 512 tokens
Chunk 817: 512 tokens
Chunk 818: 512 tokens
Chunk 819: 512 tokens
Chunk 820: 512 tokens
Chunk 821: 512 tokens
Chunk 822: 512 tokens
Chunk 823: 512 tokens
Chunk 824: 512 tokens
Chunk 825: 512 tokens
Chunk 826: 512 tokens
Chunk 827: 512 tokens
Chunk 828: 512 tokens
Chunk 829: 512 tokens
Chunk 830: 512 tokens
Chunk 831: 512 tokens
Chunk 832: 512 tokens
Chunk 833: 512 tokens
Chunk 834: 512 tokens
Chunk 835: 512 tokens
Chunk 836: 512 tokens
Chunk 837: 512 tokens
Chunk 838: 512 tokens
Chunk 839: 512 tokens
Chunk 840: 512 tokens
Chunk 841: 512 tokens
Chunk 842: 512 tokens
Chunk 843: 512 tokens
Chunk 844: 512 tokens
Chunk 845: 512 tokens
Chunk 846: 512 tokens
Chunk 847: 512 tokens
Chunk 848: 512 tokens
Chunk 849: 512 tokens
Chunk 850: 512 tokens
Chunk 851: 512 tokens
Chunk 852: 512 tokens
Chunk 853: 512 tokens
Chunk 854: 512 tokens
Chunk 855: 512 tokens
Chunk 856: 512 tokens
Chunk 857: 512 tokens
Chunk 858: 512 tokens
Chunk 859: 512 tokens
Chunk 860: 512 tokens
Chunk 861: 512 tokens
Chunk 862: 512 tokens
Chunk 863: 512 tokens
Chunk 864: 512 tokens
Chunk 865: 512 tokens
Chunk 866: 512 tokens
Chunk 867: 512 tokens
Chunk 868: 512 tokens
Chunk 869: 512 tokens
Chunk 870: 512 tokens
Chunk 871: 512 tokens
Chunk 872: 512 tokens
Chunk 873: 512 tokens
Chunk 874: 512 tokens
Chunk 875: 512 tokens
Chunk 876: 512 tokens
Chunk 877: 512 tokens
Chunk 878: 512 tokens
Chunk 879: 512 tokens
Chunk 880: 512 tokens
Chunk 881: 512 tokens
Chunk 882: 512 tokens
Chunk 883: 512 tokens
Chunk 884: 512 tokens
Chunk 885: 512 tokens
Chunk 886: 512 tokens
Chunk 887: 512 tokens
Chunk 888: 512 tokens
Chunk 889: 512 tokens
Chunk 890: 512 tokens
Chunk 891: 512 tokens
Chunk 892: 512 tokens
Chunk 893: 512 tokens
Chunk 894: 512 tokens
Chunk 895: 512 tokens
Chunk 896: 512 tokens
Chunk 897: 512 tokens
Chunk 898: 512 tokens
Chunk 899: 512 tokens
Chunk 900: 512 tokens
Chunk 901: 512 tokens
Chunk 902: 512 tokens
Chunk 903: 512 tokens
Chunk 904: 512 tokens
Chunk 905: 512 tokens
Chunk 906: 512 tokens
Chunk 907: 512 tokens
Chunk 908: 512 tokens
Chunk 909: 512 tokens
Chunk 910: 512 tokens

In [30]:
from transformers import AutoTokenizer

# Load the tokenizer for our existing DistilBERT model
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

MAX_LENGTH = 512
CHUNK_SIZE = 480
OVERLAP = 50

def chunk_email(text):
    """
    Split an email into overlapping chunks that DistilBERT can process.
    """

    # Convert email into tokens
    tokens = tokenizer.encode(
        str(text),
        add_special_tokens=False
    )

    chunks = []

    # Split into chunks
    start = 0

    while start < len(tokens):
        end = start + CHUNK_SIZE
        chunk_tokens = tokens[start:end]

        # Convert tokens back to text
        chunk_text = tokenizer.decode(
            chunk_tokens,
            skip_special_tokens=True
        )

        chunks.append(chunk_text)

        # Move forward while keeping overlap
        start += CHUNK_SIZE - OVERLAP

    return chunks

In [32]:
test_email = df["Email Text"].iloc[0]

chunks = chunk_email(test_email)

print("Number of chunks:", len(chunks))

for i, chunk in enumerate(chunks):
    token_count = len(
        tokenizer.encode(
            chunk,
            add_special_tokens=True
        )
    )
    print(f"Chunk {i+1}: {token_count} tokens")

Number of chunks: 1
Chunk 1: 254 tokens

In [33]:
long_email = df.loc[
    df["Email Text"].map(
        lambda x: len(tokenizer.encode(
            str(x),
            add_special_tokens=False
        ))
    ).idxmax(),
    "Email Text"
]

print("Characters:", len(long_email))

long_chunks = chunk_email(long_email)

print("Number of chunks:", len(long_chunks))

print("\nFirst 5 chunks:")

for i, chunk in enumerate(long_chunks[:5]):
    token_count = len(
        tokenizer.encode(
            chunk,
            add_special_tokens=True
        )
    )
    print(f"Chunk {i+1}: {token_count} tokens")

Token indices sequence length is longer than the specified maximum sequence length for this model (614 > 512). Running this sequence through the model will result in indexing errors

Characters: 17036692
Number of chunks: 9610

First 5 chunks:
Chunk 1: 482 tokens
Chunk 2: 482 tokens
Chunk 3: 482 tokens
Chunk 4: 482 tokens
Chunk 5: 482 tokens

In [34]:
# ============================================================
# STEP 9: Convert our Pandas dataframes into Hugging Face
# Dataset objects
# ============================================================

from datasets import Dataset

# Keep ONLY the two columns required for training:
#   Email Text -> the input to DistilBERT
#   label      -> 0 = legitimate, 1 = phishing
train_dataset = Dataset.from_pandas(
    train_df[["Email Text", "label"]],
    preserve_index=False
)

val_dataset = Dataset.from_pandas(
    val_df[["Email Text", "label"]],
    preserve_index=False
)

test_dataset = Dataset.from_pandas(
    test_df[["Email Text", "label"]],
    preserve_index=False
)

print("Training dataset:")
print(train_dataset)

print("\nValidation dataset:")
print(val_dataset)

print("\nTest dataset:")
print(test_dataset)

Training dataset:
Dataset({
    features: ['Email Text', 'label'],
    num_rows: 14011
})

Validation dataset:
Dataset({
    features: ['Email Text', 'label'],
    num_rows: 1751
})

Test dataset:
Dataset({
    features: ['Email Text', 'label'],
    num_rows: 1752
})

In [35]:
# ============================================================
# STEP 10: Tokenization
# ============================================================

MAX_LENGTH = 512

def tokenize_emails(batch):
    """
    Convert email text into DistilBERT input tokens.

    truncation=True:
        Ensures no input passed to the model is longer than
        DistilBERT's 512-token limit.

    max_length=512:
        Maximum sequence length supported by our model.
    """

    return tokenizer(
        batch["Email Text"],
        truncation=True,
        max_length=MAX_LENGTH
    )


# Tokenize the training set
train_tokenized = train_dataset.map(
    tokenize_emails,
    batched=True,
    remove_columns=["Email Text"]
)

# Tokenize the validation set
val_tokenized = val_dataset.map(
    tokenize_emails,
    batched=True,
    remove_columns=["Email Text"]
)

# Tokenize the test set
test_tokenized = test_dataset.map(
    tokenize_emails,
    batched=True,
    remove_columns=["Email Text"]
)

print("Tokenization complete!")
print(train_tokenized)

Map:   0%|          | 0/14011 [00:00<?, ? examples/s]

Map:   0%|          | 0/1751 [00:00<?, ? examples/s]

Map:   0%|          | 0/1752 [00:00<?, ? examples/s]

Tokenization complete!
Dataset({
    features: ['label', 'input_ids', 'attention_mask'],
    num_rows: 14011
})

In [36]:
# ============================================================
# STEP 11: Verify tokenization
# ============================================================

print("First training example:")
print(train_tokenized[0])

print("\nNumber of input tokens:",
      len(train_tokenized[0]["input_ids"]))

print("\nLabel:",
      train_tokenized[0]["label"])

First training example:
{'label': 0, 'input_ids': [101, 20604, 20231, 1998, 19476, 2655, 2005, 4981, 3034, 1024, 1996, 20231, 1997, 20604, 4155, 1006, 2238, 2656, 1011, 2676, 1007, 8395, 1024, 1996, 19476, 1997, 20604, 4155, 1006, 2238, 2603, 1007, 2044, 1037, 2200, 3144, 2034, 20604, 20231, 3034, 2012, 15529, 2378, 2089, 2687, 1010, 1996, 2533, 1997, 15397, 2012, 1996, 2118, 1997, 4307, 2012, 27929, 1011, 28843, 18675, 29474, 2005, 1996, 2117, 20604, 20231, 3034, 2000, 2022, 2218, 2238, 2656, 1011, 2676, 1010, 2639, 1012, 1996, 3034, 2097, 2022, 11677, 2011, 1037, 8395, 2239, 20604, 19476, 2000, 2022, 2218, 2238, 2603, 1010, 2639, 1012, 2119, 2824, 2097, 2202, 2173, 2076, 1996, 12158, 2554, 1997, 2637, 2621, 2820, 1006, 2238, 17465, 1011, 2251, 2382, 1007, 2029, 2097, 2022, 2218, 2012, 1996, 2118, 1997, 4307, 2012, 27929, 1011, 28843, 1006, 4037, 1024, 8299, 1024, 1013, 1013, 7479, 1012, 10272, 2386, 1012, 21318, 14194, 1012, 3968, 2226, 1013, 17002, 7076, 2102, 1007, 1012, 6818, 2097, 2022, 3479, 2006, 1996, 3978, 1997, 5330, 2094, 10812, 29474, 1010, 2000, 2022, 13224, 2011, 1037, 4989, 2837, 1012, 2169, 2831, 2097, 2022, 2871, 2781, 2146, 2007, 2019, 3176, 16068, 2781, 2005, 6594, 1012, 3531, 4604, 2184, 4809, 1997, 2019, 10812, 10061, 1010, 2012, 2087, 1016, 1011, 5530, 2146, 1006, 2164, 4973, 1998, 7604, 1007, 1012, 3531, 4372, 20464, 9232, 1037, 1017, 2595, 2629, 4003, 2007, 6342, 25526, 14643, 3258, 5517, 2171, 1997, 3259, 1010, 2171, 1997, 3166, 1010, 12912, 1998, 4769, 1010, 2164, 1041, 1011, 5653, 4769, 1010, 3042, 2193, 1010, 1998, 5769, 4415, 3251, 1996, 23298, 2003, 2005, 1996, 3034, 2030, 1996, 8395, 1012, 1996, 2171, 1997, 1996, 3166, 5807, 4140, 3711, 2006, 1996, 10061, 1012, 27842, 2011, 1041, 1011, 5653, 2030, 6904, 2595, 2097, 2025, 2022, 3970, 1012, 29474, 2323, 2022, 2695, 10665, 2098, 2053, 2101, 2084, 2233, 2321, 1010, 2639, 1010, 1998, 2741, 2000, 1024, 17532, 3841, 2863, 5302, 4609, 1012, 2533, 1997, 15397, 1010, 2871, 2620, 2620, 13109, 2497, 1012, 2118, 1997, 4307, 2012, 27929, 1011, 28843, 1012, 27929, 1010, 6335, 6079, 17914, 2487, 10383, 3034, 4037, 1024, 8299, 1024, 1013, 1013, 7479, 1012, 10272, 2386, 1012, 21318, 14194, 1012, 3968, 2226, 1013, 2967, 1013, 20116, 1013, 17002, 7076, 2102, 1013, 9281, 1013, 20604, 1012, 16129, 3531, 4638, 2041, 1996, 20604, 15397, 8264, 2073, 19106, 4981, 2006, 20604, 4155, 2064, 2022, 6866, 1998, 22817, 1012, 1996, 4769, 2003, 1024, 8299, 1024, 1013, 1013, 7479, 1012, 15529, 1012, 3968, 2226, 1013, 29466, 1013, 5869, 1013, 15397, 1013, 20604, 1013, 3531, 3622, 2035, 27050, 2055, 1996, 3034, 1998, 8395, 2000, 1024, 17532, 3841, 2863, 5302, 4609, 10373, 1024, 1041, 1011, 3841, 2863, 1030, 21318, 14194, 1012, 3968, 2226, 10093, 1024, 1006, 20335, 1007, 21211, 1011, 6390, 24594, 6904, 2595, 1024, 1006, 19883, 1007, 21211, 1011, 4090, 28756, 10863, 2837, 3312, 20118, 4609, 1006, 15529, 1007, 17532, 3841, 2863, 5302, 4609, 1006, 21318, 14194, 1007, 5292, 23806, 8501, 2099, 1006, 15529, 1007, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

Number of input tokens: 479

Label: 0

In [37]:
# Check that no tokenized training example exceeds 512 tokens

max_length_found = max(
    len(example["input_ids"])
    for example in train_tokenized
)

print("Maximum tokenized length:", max_length_found)

Maximum tokenized length: 512

In [38]:
# ============================================================
# STEP 12: Data Collator
# ============================================================

from transformers import DataCollatorWithPadding

# Dynamically pads emails within each batch.
#
# This is more memory-efficient than padding every email
# to 512 tokens before training.
data_collator = DataCollatorWithPadding(
    tokenizer=tokenizer
)

print("Data collator ready.")

Data collator ready.

In [39]:
# ============================================================
# STEP 13: Move DistilBERT to the GPU
# ============================================================

import torch

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

model.to(device)

print("Using device:", device)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

Using device: cuda
GPU: Tesla T4

In [40]:
# ============================================================
# STEP 14: Configure DistilBERT Training
# ============================================================

import numpy as np
import torch

from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    roc_auc_score
)

from transformers import (
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback
)


# ------------------------------------------------------------
# 1. Evaluation metrics
# ------------------------------------------------------------
# We calculate more than accuracy because phishing detection
# needs to consider false negatives and false positives.
#
# label:
#   0 = legitimate
#   1 = phishing
#
# The model produces logits for both classes.
# We convert them into probabilities using softmax.
# ------------------------------------------------------------

def compute_metrics(eval_pred):

    logits, labels = eval_pred

    # Convert logits → probabilities
    probabilities = torch.softmax(
        torch.tensor(logits),
        dim=-1
    ).numpy()

    # Probability of phishing
    phishing_probability = probabilities[:, 1]

    # Default classification threshold
    predictions = (
        phishing_probability >= 0.50
    ).astype(int)

    # Calculate metrics
    accuracy = accuracy_score(
        labels,
        predictions
    )

    precision, recall, f1, _ = (
        precision_recall_fscore_support(
            labels,
            predictions,
            average="binary",
            zero_division=0
        )
    )

    roc_auc = roc_auc_score(
        labels,
        phishing_probability
    )

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "roc_auc": roc_auc
    }


# ------------------------------------------------------------
# 2. Training configuration
# ------------------------------------------------------------

training_args = TrainingArguments(

    # Where checkpoints will temporarily be stored
    output_dir="./distilbert_checkpoints",

    # Train for 3 complete passes through the training data
    num_train_epochs=3,

    # Standard fine-tuning learning rate for BERT-family models
    learning_rate=2e-5,

    # Helps prevent excessive overfitting
    weight_decay=0.01,

    # Number of examples processed at once
    per_device_train_batch_size=16,

    # Validation batch size can be larger because
    # gradients aren't calculated during evaluation
    per_device_eval_batch_size=32,

    # Gradually increase learning rate at the beginning
    warmup_ratio=0.1,

    # Evaluate after every epoch
    eval_strategy="epoch",

    # Save a checkpoint after every epoch
    save_strategy="epoch",

    # Keep the checkpoint with the best validation F1
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,

    # Show training progress
    logging_steps=50,

    # Don't send anything to external experiment trackers
    report_to="none",

    # Reproducibility
    seed=42,

    # Use T4 mixed precision to reduce GPU memory usage
    fp16=torch.cuda.is_available()
)

print("Training configuration created successfully.")
print(training_args)

Training configuration created successfully.
TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=True,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=True,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=2e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=./distilbert_checkpoints/runs/Aug30_03-51-06_4e692a0321b1,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=50,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs=None,
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=f1,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=3,
optim=OptimizerNames.ADAMW_TORCH_FUSED,
optim_args=None,
optim_target_modules=None,
output_dir=./distilbert_checkpoints,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=16,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [41]:
# ============================================================
# STEP 15: Create the Hugging Face Trainer
# ============================================================

trainer = Trainer(

    # Our DistilBERT model
    model=model,

    # Training configuration from Step 14
    args=training_args,

    # Training data
    train_dataset=train_tokenized,

    # Validation data
    eval_dataset=val_tokenized,

    # Tokenizer
    processing_class=tokenizer,

    # Dynamic padding
    data_collator=data_collator,

    # Accuracy / Precision / Recall / F1 / ROC-AUC
    compute_metrics=compute_metrics,

    # Stop if validation F1 stops improving
    callbacks=[
        EarlyStoppingCallback(
            early_stopping_patience=1
        )
    ]
)

print("Trainer created successfully.")

Trainer created successfully.

In [42]:
# ============================================================
# STEP 16: Final pre-training check
# ============================================================

print("Model device:", next(model.parameters()).device)
print("Training examples:", len(train_tokenized))
print("Validation examples:", len(val_tokenized))
print("Test examples:", len(test_tokenized))
print("Batch size:", training_args.per_device_train_batch_size)
print("Epochs:", training_args.num_train_epochs)
print("Learning rate:", training_args.learning_rate)

Model device: cuda:0
Training examples: 14011
Validation examples: 1751
Test examples: 1752
Batch size: 16
Epochs: 3
Learning rate: 2e-05

In [43]:
# ============================================================
# STEP 17: TRAIN THE FINAL DISTILBERT MODEL
# ============================================================

print("Starting DistilBERT training...")
print("GPU:", torch.cuda.get_device_name(0))
print()

train_result = trainer.train()

print("\n================================================")
print("TRAINING COMPLETE")
print("================================================")

print("\nTraining statistics:")
print(train_result)

Starting DistilBERT training...
GPU: Tesla T4

================================================
TRAINING COMPLETE
================================================

Training statistics:
TrainOutput(global_step=2628, training_loss=0.06639969708962165, metrics={'train_runtime': 622.3952, 'train_samples_per_second': 67.534, 'train_steps_per_second': 4.222, 'total_flos': 5559176527272192.0, 'train_loss': 0.06639969708962165, 'epoch': 3.0})

In [44]:
# ============================================================
# STEP 18: FINAL TEST EVALUATION
# ============================================================

print("Evaluating the final DistilBERT model on the")
print("completely untouched TEST dataset...\n")

test_results = trainer.evaluate(
    eval_dataset=test_tokenized
)

print("\n================================================")
print("FINAL TEST RESULTS")
print("================================================")

for metric, value in test_results.items():
    if isinstance(value, float):
        print(f"{metric}: {value:.4f}")
    else:
        print(f"{metric}: {value}")

Evaluating the final DistilBERT model on the
completely untouched TEST dataset...

================================================
FINAL TEST RESULTS
================================================
eval_loss: 0.0347
eval_accuracy: 0.9932
eval_precision: 0.9938
eval_recall: 0.9878
eval_f1: 0.9908
eval_roc_auc: 0.9995
eval_runtime: 10.3364
eval_samples_per_second: 169.4980
eval_steps_per_second: 5.3210
epoch: 3.0000

In [45]:
# ============================================================
# STEP 19: LOAD EXTERNAL DATASET
# ============================================================

from datasets import load_dataset

external_dataset = load_dataset(
    "jmmrcp/Phishing-IBM-Dataset"
)

print(external_dataset)

README.md:   0%|          | 0.00/470 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/3.98M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/1.00M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/13337 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/3335 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['index', 'message', 'Classify'],
        num_rows: 13337
    })
    test: Dataset({
        features: ['index', 'message', 'Classify'],
        num_rows: 3335
    })
})

In [46]:
# Show the columns in the external dataset

for split_name, split_data in external_dataset.items():
    print("\nSplit:", split_name)
    print("Columns:", split_data.column_names)
    print("Number of examples:", len(split_data))
    print("\nFirst example:")
    print(split_data[0])

Split: train
Columns: ['index', 'message', 'Classify']
Number of examples: 13337

First example:
{'index': 8213, 'message': 'expense ground rules what level of expense do you want to be notified about ? ( e . g . i want to authorise kal to spend about $ 5 , 000 over the next couple of weeks on preliminary work for marketing materials to support a relaunch of enrononline ) dave', 'Classify': 'Normal'}

Split: test
Columns: ['index', 'message', 'Classify']
Number of examples: 3335

First example:
{'index': 17671, 'message': "meds ? we have it all right here effort make heads turn by wearing one of this season ' s most coveted wholesale repliica bags , watches or whatever luxury ! start shopping today and find out why so many other women are choosing to carry our products year round . http : / / aaqa . starsleekgreat . com / li / addidas , bally , bvlgari , burberry , cartier , chanel , christian dior , dunhill , dupont , escada , fendi , ferragamo , gucci , hermes , iwc , jacob & co . , louis vuitton , mont blanc , movado , nike , omega , oris , prada , puma , rado , roger dubuis , rolex , sector , tag heuer , technomarine , tiffany , timberland , tudor it ' s gotta blast , get outta control * nothing can stop us now if you say , that it ' s okaywe gotta start right now frol eurolijsten drawot gdo 2 ellisman esahc   give me ten wheels for jesus !   - elvis hitler", 'Classify': 'Phishing'}

In [47]:
# ============================================================
# STEP 19.1: INSPECT EXTERNAL DATASET LABELS
# ============================================================

# Get the external test set
external_test = external_dataset["test"]

# Show all unique label values
print("Unique labels:")
print(set(external_test["Classify"]))

# Show the distribution
print("\nLabel distribution:")
from collections import Counter

print(Counter(external_test["Classify"]))

# Show a few examples
print("\nFirst 5 examples:")

for i in range(5):
    print("\nExample", i + 1)
    print("Label :", external_test[i]["Classify"])
    print("Text  :", external_test[i]["message"][:300])

Unique labels:
{'Normal', 'Phishing'}

Label distribution:
Counter({'Normal': 1686, 'Phishing': 1649})

First 5 examples:

Example 1
Label : Phishing
Text  : meds ? we have it all right here effort make heads turn by wearing one of this season ' s most coveted wholesale repliica bags , watches or whatever luxury ! start shopping today and find out why so many other women are choosing to carry our products year round . http : / / aaqa . starsleekgreat . c

Example 2
Label : Normal
Text  : hpl nom for october 6 , 2000 ( see attached file : hpll 006 . xls ) - hpll 006 . xls

Example 3
Label : Phishing
Text  : re : new page hi sweetie , come see the most beautiful , sweet . . . - - > 18 year old girls bare it all ! < - - http : / / freexmovies . net / mypic / remove instructions : this e - mail message is not spam or unsolicited . this e - mail address has joined or requested information in the past . if

Example 4
Label : Normal
Text  : re : budget and a lemmons jr . , billy subject : re : budget and a lemmons jr . , billy subject : re : budget and a lemmons jr . , billy subject : budget and a & a allocations so here ' s my question . is there any possibility that we will be not doing the standard bonusses ( which have caused huge

Example 5
Label : Normal
Text  : greeting from charles dear molly : happy new year ! haven  , t talked to you for a while , hope you and your family had a great holiday . i can  , t believe we are already in 2001 ! i remember we had talk last december , and you were basically waiting for the response from vince , have you heard a

In [48]:
# ============================================================
# STEP 20: EXTERNAL DATASET EVALUATION
# ============================================================
#
# IMPORTANT:
# We are NOT training on this dataset.
#
# This is an independent test of our already-trained
# DistilBERT model.
# ============================================================

import numpy as np
import torch

from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    roc_auc_score,
    confusion_matrix
)

# ------------------------------------------------------------
# 1. Get the external TEST dataset
# ------------------------------------------------------------

external_test = external_dataset["test"]

# Extract email text
external_texts = external_test["message"]

# Convert labels:
# Normal   = 0
# Phishing = 1

external_labels = np.array([
    1 if label == "Phishing" else 0
    for label in external_test["Classify"]
])

print("External test emails:", len(external_texts))
print("Normal:", np.sum(external_labels == 0))
print("Phishing:", np.sum(external_labels == 1))


# ------------------------------------------------------------
# 2. Put model in evaluation mode
# ------------------------------------------------------------

model.eval()

# Make sure model is on the GPU
model.to(device)


# ------------------------------------------------------------
# 3. Run predictions in batches
# ------------------------------------------------------------
#
# We use batches instead of processing all 3,335 emails
# simultaneously, which keeps GPU memory under control.
# ------------------------------------------------------------

BATCH_SIZE = 32

all_phishing_probabilities = []

for start in range(0, len(external_texts), BATCH_SIZE):

    # Select one batch
    batch_texts = external_texts[
        start:start + BATCH_SIZE
    ]

    # Tokenize
    inputs = tokenizer(
        batch_texts,
        padding=True,
        truncation=True,
        max_length=512,
        return_tensors="pt"
    )

    # Move tensors to GPU
    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    # No gradients needed during evaluation
    with torch.no_grad():

        outputs = model(**inputs)

        # Convert logits → probabilities
        probabilities = torch.softmax(
            outputs.logits,
            dim=-1
        )

        # Probability of PHISHING
        phishing_probs = probabilities[:, 1]

        all_phishing_probabilities.extend(
            phishing_probs.cpu().numpy()
        )


# Convert to NumPy array
all_phishing_probabilities = np.array(
    all_phishing_probabilities
)


# ------------------------------------------------------------
# 4. Convert probabilities into predictions
# ------------------------------------------------------------

THRESHOLD = 0.50

external_predictions = (
    all_phishing_probabilities >= THRESHOLD
).astype(int)


# ------------------------------------------------------------
# 5. Calculate metrics
# ------------------------------------------------------------

accuracy = accuracy_score(
    external_labels,
    external_predictions
)

precision, recall, f1, _ = (
    precision_recall_fscore_support(
        external_labels,
        external_predictions,
        average="binary",
        zero_division=0
    )
)

roc_auc = roc_auc_score(
    external_labels,
    all_phishing_probabilities
)

cm = confusion_matrix(
    external_labels,
    external_predictions
)


# ------------------------------------------------------------
# 6. Display final external results
# ------------------------------------------------------------

print("\n")
print("================================================")
print("EXTERNAL DATASET RESULTS")
print("================================================")

print(f"Accuracy :  {accuracy:.4f}")
print(f"Precision:  {precision:.4f}")
print(f"Recall   :  {recall:.4f}")
print(f"F1 Score :  {f1:.4f}")
print(f"ROC-AUC  :  {roc_auc:.4f}")

print("\nConfusion Matrix:")
print(cm)

print("\n================================================")

External test emails: 3335
Normal: 1686
Phishing: 1649


================================================
EXTERNAL DATASET RESULTS
================================================
Accuracy :  0.9901
Precision:  0.9939
Recall   :  0.9861
F1 Score :  0.9900
ROC-AUC  :  0.9994

Confusion Matrix:
[[1676   10]
 [  23 1626]]

================================================

In [49]:
# ============================================================
# STEP 21: SAVE THE FINAL DISTILBERT MODEL
# ============================================================

import os
import json

# Final model directory
FINAL_MODEL_DIR = "./distilbert_model_final"

os.makedirs(FINAL_MODEL_DIR, exist_ok=True)

# ------------------------------------------------------------
# Save the trained DistilBERT model
# ------------------------------------------------------------

trainer.save_model(FINAL_MODEL_DIR)

# ------------------------------------------------------------
# Save the tokenizer
# ------------------------------------------------------------

tokenizer.save_pretrained(FINAL_MODEL_DIR)

# ------------------------------------------------------------
# Save our label mapping
# ------------------------------------------------------------

label_mapping = {
    "0": "legitimate",
    "1": "phishing"
}

with open(
    f"{FINAL_MODEL_DIR}/label_mapping.json",
    "w"
) as f:
    json.dump(label_mapping, f, indent=4)

print("FINAL MODEL SAVED")
print("------------------")

print(os.listdir(FINAL_MODEL_DIR))

FINAL MODEL SAVED
------------------
['tokenizer_config.json', 'training_args.bin', 'tokenizer.json', 'config.json', 'label_mapping.json', 'vocab.txt', 'special_tokens_map.json', 'model.safetensors']

In [50]:
# ============================================================
# CyberMail Intelligence
# DistilBERT Phishing Email Classifier
# ============================================================
#
# This module loads the FINAL trained DistilBERT model and
# provides one simple function:
#
#     classifier.predict(email_body)
#
# The backend will eventually send the COMPLETE email body
# to this class.
#
# The class handles:
#   1. Short emails
#   2. Long emails using overlapping chunks
#   3. Chunk-level predictions
#   4. Email-level probability aggregation
#
# ============================================================

import json
import os

import torch
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification
)


class DistilBERTPhishingClassifier:

    def __init__(
        self,
        model_dir="distilbert_model_final",
        max_length=512,
        chunk_size=480,
        overlap=50
    ):
        """
        Load the FINAL DistilBERT model.

        Parameters
        ----------
        model_dir : str
            Folder containing model.safetensors and tokenizer files.

        max_length : int
            Maximum sequence length supported by DistilBERT.

        chunk_size : int
            Number of actual email tokens in each chunk.

        overlap : int
            Number of tokens shared between consecutive chunks.
        """

        # ----------------------------------------------------
        # Basic configuration
        # ----------------------------------------------------

        self.model_dir = model_dir
        self.max_length = max_length
        self.chunk_size = chunk_size
        self.overlap = overlap

        # ----------------------------------------------------
        # Select GPU if available
        # ----------------------------------------------------

        self.device = torch.device(
            "cuda" if torch.cuda.is_available() else "cpu"
        )

        # ----------------------------------------------------
        # Load tokenizer
        # ----------------------------------------------------

        self.tokenizer = AutoTokenizer.from_pretrained(
            self.model_dir
        )

        # ----------------------------------------------------
        # Load FINAL trained model
        # ----------------------------------------------------

        self.model = AutoModelForSequenceClassification.from_pretrained(
            self.model_dir
        )

        # Move model to GPU / CPU
        self.model.to(self.device)

        # Evaluation mode
        self.model.eval()

        # ----------------------------------------------------
        # Load label mapping
        # ----------------------------------------------------

        mapping_path = os.path.join(
            self.model_dir,
            "label_mapping.json"
        )

        if os.path.exists(mapping_path):

            with open(mapping_path, "r") as f:
                self.label_mapping = json.load(f)

        else:

            # Fallback mapping
            self.label_mapping = {
                "0": "legitimate",
                "1": "phishing"
            }

        print("DistilBERT loaded successfully.")
        print("Device:", self.device)

    # ========================================================
    # TOKENIZE EMAIL INTO OVERLAPPING CHUNKS
    # ========================================================

    def _create_chunks(self, email_body):
        """
        Convert a potentially long email into overlapping chunks.

        Every chunk stays below DistilBERT's 512-token limit.
        """

        # Convert text → token IDs
        tokens = self.tokenizer.encode(
            email_body,
            add_special_tokens=False
        )

        # Short email:
        # no chunking required
        if len(tokens) <= self.chunk_size:

            return [email_body]

        chunks = []

        # How far we move forward after every chunk
        step = self.chunk_size - self.overlap

        start = 0

        while start < len(tokens):

            # Select this chunk
            chunk_tokens = tokens[
                start:start + self.chunk_size
            ]

            # Convert tokens back into text
            chunk_text = self.tokenizer.decode(
                chunk_tokens,
                skip_special_tokens=True
            )

            chunks.append(chunk_text)

            # Move forward while retaining overlap
            start += step

        return chunks

    # ========================================================
    # PREDICT ONE CHUNK
    # ========================================================

    @torch.inference_mode()
    def _predict_chunk(self, chunk):
        """
        Predict phishing probability for one chunk.
        """

        # Tokenize the chunk
        inputs = self.tokenizer(
            chunk,
            return_tensors="pt",
            truncation=True,
            max_length=self.max_length
        )

        # Move tensors to same device as model
        inputs = {
            key: value.to(self.device)
            for key, value in inputs.items()
        }

        # Run DistilBERT
        outputs = self.model(**inputs)

        # Convert logits → probabilities
        probabilities = torch.softmax(
            outputs.logits,
            dim=-1
        )[0]

        # Class 0 = legitimate
        # Class 1 = phishing

        legitimate_probability = float(
            probabilities[0].cpu()
        )

        phishing_probability = float(
            probabilities[1].cpu()
        )

        return {
            "legitimate_probability": legitimate_probability,
            "phishing_probability": phishing_probability
        }

    # ========================================================
    # PREDICT COMPLETE EMAIL
    # ========================================================

    def predict(self, email_body):
        """
        Analyze a complete email body.

        Returns ONE email-level result.
        """

        # ----------------------------------------------------
        # Basic input validation
        # ----------------------------------------------------

        if email_body is None:

            raise ValueError(
                "email_body cannot be None"
            )

        email_body = str(email_body).strip()

        if not email_body:

            raise ValueError(
                "email_body cannot be empty"
            )

        # ----------------------------------------------------
        # Create chunks
        # ----------------------------------------------------

        chunks = self._create_chunks(
            email_body
        )

        # ----------------------------------------------------
        # Predict each chunk
        # ----------------------------------------------------

        chunk_results = []

        for chunk in chunks:

            result = self._predict_chunk(
                chunk
            )

            chunk_results.append(result)

        # ----------------------------------------------------
        # Aggregate chunk probabilities
        # ----------------------------------------------------
        #
        # We use MAX here deliberately.
        #
        # If one section of a long email strongly indicates
        # phishing, we don't want several harmless sections
        # to dilute that signal.
        #
        # Example:
        #
        # Chunk 1 → 0.04
        # Chunk 2 → 0.11
        # Chunk 3 → 0.96  ← suspicious section
        # Chunk 4 → 0.08
        #
        # Email probability → 0.96
        #
        # ----------------------------------------------------

        phishing_probability = max(
            result["phishing_probability"]
            for result in chunk_results
        )

        legitimate_probability = 1.0 - phishing_probability

        # ----------------------------------------------------
        # Final classification
        # ----------------------------------------------------

        threshold = 0.50

        if phishing_probability >= threshold:

            label = 1
            classification = "phishing"

        else:

            label = 0
            classification = "legitimate"

        # ----------------------------------------------------
        # Return backend-friendly result
        # ----------------------------------------------------

        return {
            "label": label,
            "class": classification,

            "phishing_probability": round(
                phishing_probability,
                6
            ),

            "legitimate_probability": round(
                legitimate_probability,
                6
            ),

            "chunks_analyzed": len(
                chunks
            ),

            "threshold": threshold
        }

In [51]:
# ============================================================
# STEP 23: LOAD THE SAVED MODEL
# ============================================================

from inference import DistilBERTPhishingClassifier

classifier = DistilBERTPhishingClassifier(
    model_dir="./distilbert_model_final"
)

In [52]:
# ============================================================
# STEP 24: TEST PHISHING EMAIL
# ============================================================

phishing_email = """
URGENT SECURITY ALERT

Your account has been temporarily suspended due to
suspicious activity.

You must verify your account immediately to avoid permanent
closure.

Click the link below and enter your username, password,
and banking information.

Failure to verify your account within 24 hours will result
in permanent suspension.
"""

result = classifier.predict(phishing_email)

print(result)

{'label': 1, 'class': 'phishing', 'phishing_probability': 0.9976997971534729, 'legitimate_probability': 0.0023001530207693577, 'threshold': 0.5}

In [53]:
# ============================================================
# STEP 25: TEST LEGITIMATE EMAIL
# ============================================================

legitimate_email = """
Hi Ananya,

Just a reminder that our project meeting is scheduled
for tomorrow at 10 AM.

Please bring the updated presentation and the latest
testing results.

Thanks,
Project Team
"""

result = classifier.predict(legitimate_email)

print(result)

{'label': 0, 'class': 'legitimate', 'phishing_probability': 0.00011470039316918701, 'legitimate_probability': 0.9998853206634521, 'threshold': 0.5}

In [54]:
# ============================================================
# STEP 26: TEST LONG EMAIL HANDLING
# ============================================================

# Repeat legitimate text enough times to exceed 512 tokens
long_email = """
Hi team,

This is a routine project update.
Our meeting is scheduled for tomorrow.
Please review the documents before the meeting.
Thank you.
""" * 200

result = classifier.predict(long_email)

print(result)

{'label': 0, 'class': 'legitimate', 'phishing_probability': 0.00010417099838377908, 'legitimate_probability': 0.9998958110809326, 'threshold': 0.5}

In [55]:
# ============================================================
# STEP 27: VERIFY INFERENCE MODULE
# ============================================================

import inspect

print(inspect.getsource(classifier.predict))

    @torch.inference_mode()
    def predict(self, email_body: str):
        email_body = str(email_body or "").strip()

        inputs = self.tokenizer(
            email_body,
            return_tensors="pt",
            truncation=True,
            max_length=512,
        )
        inputs = {k: v.to(self.device) for k, v in inputs.items()}

        outputs = self.model(**inputs)
        probabilities = torch.softmax(outputs.logits, dim=-1)[0]

        phishing_probability = float(probabilities[1].cpu())
        legitimate_probability = float(probabilities[0].cpu())

        label = int(phishing_probability >= self.threshold)

        return {
            "label": label,
            "class": "phishing" if label else "legitimate",
            "phishing_probability": phishing_probability,
            "legitimate_probability": legitimate_probability,
            "threshold": self.threshold,
        }

In [56]:
print(classifier.predict(long_email))

{'label': 0, 'class': 'legitimate', 'phishing_probability': 0.00010417099838377908, 'legitimate_probability': 0.9998958110809326, 'threshold': 0.5}

In [63]:
# ============================================================
# STEP 31: WRITE THE FINAL INFERENCE MODULE
# ============================================================

%%writefile inference.py

import json
import os

import torch
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification
)


class DistilBERTPhishingClassifier:
    """
    Backend-ready wrapper for the final trained DistilBERT model.

    Input:
        Complete email body as a string.

    Output:
        One email-level phishing prediction.

    Long emails:
        Automatically split into overlapping chunks.
    """

    def __init__(
        self,
        model_dir="./distilbert_model_final",
        max_length=512,
        chunk_size=480,
        overlap=50,
        threshold=0.50
    ):

        # ----------------------------------------------------
        # Configuration
        # ----------------------------------------------------

        self.model_dir = model_dir
        self.max_length = max_length
        self.chunk_size = chunk_size
        self.overlap = overlap
        self.threshold = threshold

        # Make sure overlap is smaller than chunk size
        if overlap >= chunk_size:
            raise ValueError(
                "overlap must be smaller than chunk_size"
            )

        # ----------------------------------------------------
        # Select device
        # ----------------------------------------------------

        self.device = torch.device(
            "cuda" if torch.cuda.is_available() else "cpu"
        )

        # ----------------------------------------------------
        # Load tokenizer
        # ----------------------------------------------------

        self.tokenizer = AutoTokenizer.from_pretrained(
            self.model_dir
        )

        # We manually handle long sequences ourselves.
        # This prevents the tokenizer from warning when it
        # encounters an email longer than 512 tokens.
        self.tokenizer.model_max_length = 10**9

        # ----------------------------------------------------
        # Load FINAL trained DistilBERT
        # ----------------------------------------------------

        self.model = AutoModelForSequenceClassification.from_pretrained(
            self.model_dir
        )

        self.model.to(self.device)
        self.model.eval()

        # ----------------------------------------------------
        # Load label mapping
        # ----------------------------------------------------

        mapping_path = os.path.join(
            self.model_dir,
            "label_mapping.json"
        )

        if os.path.exists(mapping_path):

            with open(mapping_path, "r") as file:
                self.label_mapping = json.load(file)

        else:

            self.label_mapping = {
                "0": "legitimate",
                "1": "phishing"
            }

        print("DistilBERT loaded successfully.")
        print("Device:", self.device)

    # ========================================================
    # CREATE EMAIL CHUNKS
    # ========================================================

    def _create_chunks(self, email_body):
        """
        Split the complete email into overlapping token chunks.

        Each chunk contains at most 480 actual email tokens.
        DistilBERT adds its special tokens afterwards, keeping
        the final sequence safely below the 512-token limit.
        """

        # Convert the complete email into token IDs.
        #
        # IMPORTANT:
        # add_special_tokens=False because we will add them
        # automatically when passing each chunk to the model.
        tokens = self.tokenizer.encode(
            email_body,
            add_special_tokens=False
        )

        # ----------------------------------------------------
        # Short email
        # ----------------------------------------------------

        if len(tokens) <= self.chunk_size:
            return [email_body]

        # ----------------------------------------------------
        # Long email
        # ----------------------------------------------------

        chunks = []

        step = self.chunk_size - self.overlap

        start = 0

        while start < len(tokens):

            # Take one section of the email
            chunk_tokens = tokens[
                start:start + self.chunk_size
            ]

            # Convert token IDs back into text
            chunk_text = self.tokenizer.decode(
                chunk_tokens,
                skip_special_tokens=True
            )

            chunks.append(chunk_text)

            # Move forward while retaining overlap
            start += step

        return chunks

    # ========================================================
    # PREDICT ONE CHUNK
    # ========================================================

    @torch.inference_mode()
    def _predict_chunk(self, chunk):
        """
        Run DistilBERT on one chunk.
        """

        # Tokenize ONE chunk.
        #
        # Because chunk_size = 480, the resulting sequence
        # including special tokens remains <= 512.
        inputs = self.tokenizer(
            chunk,
            return_tensors="pt",
            truncation=True,
            max_length=self.max_length
        )

        # Move tensors to the same device as the model
        inputs = {
            key: value.to(self.device)
            for key, value in inputs.items()
        }

        # Run DistilBERT
        outputs = self.model(**inputs)

        # Convert logits into probabilities
        probabilities = torch.softmax(
            outputs.logits,
            dim=-1
        )[0]

        # Class 0 = legitimate
        # Class 1 = phishing

        legitimate_probability = float(
            probabilities[0].cpu()
        )

        phishing_probability = float(
            probabilities[1].cpu()
        )

        return {
            "legitimate_probability": legitimate_probability,
            "phishing_probability": phishing_probability
        }

    # ========================================================
    # PREDICT COMPLETE EMAIL
    # ========================================================

    def predict(self, email_body):
        """
        Analyze a complete email.

        Short email:
            One DistilBERT prediction.

        Long email:
            Multiple overlapping predictions are generated
            and combined into one email-level result.
        """

        # ----------------------------------------------------
        # Validate input
        # ----------------------------------------------------

        if email_body is None:
            raise ValueError(
                "email_body cannot be None"
            )

        email_body = str(email_body).strip()

        if not email_body:
            raise ValueError(
                "email_body cannot be empty"
            )

        # ----------------------------------------------------
        # Create chunks
        # ----------------------------------------------------

        chunks = self._create_chunks(
            email_body
        )

        # ----------------------------------------------------
        # Predict every chunk
        # ----------------------------------------------------

        chunk_results = []

        for chunk in chunks:

            result = self._predict_chunk(
                chunk
            )

            chunk_results.append(result)

        # ----------------------------------------------------
        # Aggregate predictions
        # ----------------------------------------------------
        #
        # MAX is used deliberately.
        #
        # If one part of a long email is strongly suspicious,
        # that signal should not be diluted by harmless sections.
        # ----------------------------------------------------

        phishing_probability = max(
            result["phishing_probability"]
            for result in chunk_results
        )

        legitimate_probability = (
            1.0 - phishing_probability
        )

        # ----------------------------------------------------
        # Final classification
        # ----------------------------------------------------

        label = int(
            phishing_probability >= self.threshold
        )

        classification = (
            "phishing"
            if label == 1
            else "legitimate"
        )

        # ----------------------------------------------------
        # Return backend-friendly JSON-compatible result
        # ----------------------------------------------------

        return {
            "label": label,
            "class": classification,
            "phishing_probability": round(
                phishing_probability,
                6
            ),
            "legitimate_probability": round(
                legitimate_probability,
                6
            ),
            "chunks_analyzed": len(chunks),
            "threshold": self.threshold
        }

Overwriting inference.py

In [64]:
# ============================================================
# STEP 28: RELOAD THE UPDATED INFERENCE MODULE
# ============================================================

import importlib
import inference

importlib.reload(inference)

from inference import DistilBERTPhishingClassifier

classifier = DistilBERTPhishingClassifier(
    model_dir="./distilbert_model_final"
)

DistilBERT loaded successfully.
Device: cuda

In [65]:
# ============================================================
# STEP 29: VERIFY CHUNKING IS REALLY ACTIVE
# ============================================================

import inspect

print(
    inspect.getsource(
        DistilBERTPhishingClassifier.predict
    )
)

    def predict(self, email_body):
        """
        Analyze a complete email.

        Short email:
            One DistilBERT prediction.

        Long email:
            Multiple overlapping predictions are generated
            and combined into one email-level result.
        """

        # ----------------------------------------------------
        # Validate input
        # ----------------------------------------------------

        if email_body is None:
            raise ValueError(
                "email_body cannot be None"
            )

        email_body = str(email_body).strip()

        if not email_body:
            raise ValueError(
                "email_body cannot be empty"
            )

        # ----------------------------------------------------
        # Create chunks
        # ----------------------------------------------------

        chunks = self._create_chunks(
            email_body
        )

        # ----------------------------------------------------
        # Predict every chunk
        # ----------------------------------------------------

        chunk_results = []

        for chunk in chunks:

            result = self._predict_chunk(
                chunk
            )

            chunk_results.append(result)

        # ----------------------------------------------------
        # Aggregate predictions
        # ----------------------------------------------------
        #
        # MAX is used deliberately.
        #
        # If one part of a long email is strongly suspicious,
        # that signal should not be diluted by harmless sections.
        # ----------------------------------------------------

        phishing_probability = max(
            result["phishing_probability"]
            for result in chunk_results
        )

        legitimate_probability = (
            1.0 - phishing_probability
        )

        # ----------------------------------------------------
        # Final classification
        # ----------------------------------------------------

        label = int(
            phishing_probability >= self.threshold
        )

        classification = (
            "phishing"
            if label == 1
            else "legitimate"
        )

        # ----------------------------------------------------
        # Return backend-friendly JSON-compatible result
        # ----------------------------------------------------

        return {
            "label": label,
            "class": classification,
            "phishing_probability": round(
                phishing_probability,
                6
            ),
            "legitimate_probability": round(
                legitimate_probability,
                6
            ),
            "chunks_analyzed": len(chunks),
            "threshold": self.threshold
        }

In [66]:
# ============================================================
# STEP 30: TEST LONG EMAIL
# ============================================================

result = classifier.predict(long_email)

print(result)

{'label': 0, 'class': 'legitimate', 'phishing_probability': 0.000177, 'legitimate_probability': 0.999823, 'chunks_analyzed': 14, 'threshold': 0.5}

In [67]:
# ============================================================
# STEP 34: VERIFY EVERY CHUNK IS WITHIN DISTILBERT'S LIMIT
# ============================================================

chunks = classifier._create_chunks(long_email)

chunk_lengths = []

for chunk in chunks:

    token_count = len(
        classifier.tokenizer(
            chunk,
            add_special_tokens=True,
            truncation=False
        )["input_ids"]
    )

    chunk_lengths.append(token_count)

print("Total chunks:", len(chunks))
print("Maximum chunk length:", max(chunk_lengths))
print("Minimum chunk length:", min(chunk_lengths))

print(
    "All chunks <= 512:",
    all(length <= 512 for length in chunk_lengths)
)

print("\nChunk lengths:")
print(chunk_lengths)

Total chunks: 14
Maximum chunk length: 482
Minimum chunk length: 12
All chunks <= 512: True

Chunk lengths:
[482, 482, 482, 482, 482, 482, 482, 482, 482, 482, 482, 482, 442, 12]

In [68]:
# ============================================================
# STEP 35: CREATE BACKEND-READY DISTILBERT PACKAGE
# ============================================================

import os
import shutil

# Final package directory
PACKAGE_DIR = "distilbert_phishing_backend"

# Remove an old package if one exists
if os.path.exists(PACKAGE_DIR):
    shutil.rmtree(PACKAGE_DIR)

# Create directories
MODEL_DIR = os.path.join(
    PACKAGE_DIR,
    "model"
)

os.makedirs(MODEL_DIR)

# ------------------------------------------------------------
# Copy the trained model files
# ------------------------------------------------------------

SOURCE_MODEL_DIR = "distilbert_model_final"

for filename in os.listdir(SOURCE_MODEL_DIR):

    source = os.path.join(
        SOURCE_MODEL_DIR,
        filename
    )

    destination = os.path.join(
        MODEL_DIR,
        filename
    )

    if os.path.isfile(source):
        shutil.copy2(
            source,
            destination
        )

# ------------------------------------------------------------
# Copy inference.py
# ------------------------------------------------------------

shutil.copy2(
    "inference.py",
    os.path.join(
        PACKAGE_DIR,
        "inference.py"
    )
)

print("Package created successfully!")
print("\nPackage contents:")

for root, dirs, files in os.walk(PACKAGE_DIR):

    level = root.replace(
        PACKAGE_DIR,
        ""
    ).count(os.sep)

    indent = "    " * level

    print(f"{indent}{os.path.basename(root)}/")

    for file in files:
        print(f"{indent}    {file}")

Package created successfully!

Package contents:
distilbert_phishing_backend/
    inference.py
    model/
        tokenizer_config.json
        training_args.bin
        tokenizer.json
        config.json
        label_mapping.json
        vocab.txt
        special_tokens_map.json
        model.safetensors

In [70]:
# ============================================================
# STEP 36: CREATE README SAFELY
# ============================================================

import os

readme_lines = [
    "# CyberMail Intelligence - DistilBERT Phishing Classifier",
    "",
    "This package contains the final fine-tuned DistilBERT model",
    "used to classify email bodies as legitimate or phishing.",
    "",
    "## Model",
    "",
    "Base model: distilbert-base-uncased",
    "Task: Binary phishing-email classification",
    "Maximum model sequence length: 512 tokens",
    "",
    "## Performance",
    "",
    "Internal held-out test:",
    "- Accuracy: 99.32%",
    "- Precision: 99.38%",
    "- Recall: 98.78%",
    "- F1: 99.08%",
    "- ROC-AUC: 99.95%",
    "",
    "External test dataset:",
    "- Accuracy: 99.01%",
    "- Precision: 99.39%",
    "- Recall: 98.61%",
    "- F1: 99.00%",
    "- ROC-AUC: 99.94%",
    "",
    "## Usage",
    "",
    "```python",
    "from inference import DistilBERTPhishingClassifier",
    "",
    'classifier = DistilBERTPhishingClassifier(model_dir="./model")',
    "",
    "result = classifier.predict(email_body)",
    "print(result)",
    "```",
    "",
    "## Long Emails",
    "",
    "Emails longer than the DistilBERT sequence limit are",
    "automatically divided into overlapping chunks.",
    "",
    "Each chunk is independently evaluated.",
    "",
    "The highest phishing probability is used as the",
    "email-level phishing probability.",
    "",
    "## Backend Integration",
    "",
    "The backend should pass the complete parsed email body",
    "to classifier.predict(email_body).",
    "",
    "The classifier returns one JSON-compatible result.",
    "",
    "The DistilBERT model does not parse .eml files itself.",
    "The email parser should extract the email body before",
    "calling the classifier.",
]

readme_path = os.path.join(
    PACKAGE_DIR,
    "README.md"
)

with open(readme_path, "w", encoding="utf-8") as file:
    file.write("\n".join(readme_lines))

print("README created successfully.")
print("Location:", readme_path)

README created successfully.
Location: distilbert_phishing_backend/README.md

In [71]:
# ============================================================
# STEP 37: VERIFY FINAL PACKAGE
# ============================================================

required_files = [
    "model/config.json",
    "model/model.safetensors",
    "model/tokenizer.json",
    "model/tokenizer_config.json",
    "model/special_tokens_map.json",
    "model/vocab.txt",
    "model/label_mapping.json",
    "inference.py",
    "README.md"
]

print("FINAL PACKAGE CHECK")
print("===================")

all_present = True

for file in required_files:

    path = os.path.join(
        PACKAGE_DIR,
        file
    )

    exists = os.path.isfile(path)

    print(
        f"{'✓' if exists else '✗'} {file}"
    )

    if not exists:
        all_present = False

print("\nPackage ready:", all_present)

FINAL PACKAGE CHECK
===================
✓ model/config.json
✓ model/model.safetensors
✓ model/tokenizer.json
✓ model/tokenizer_config.json
✓ model/special_tokens_map.json
✓ model/vocab.txt
✓ model/label_mapping.json
✓ inference.py
✓ README.md

Package ready: True

In [72]:
# ============================================================
# STEP 38: CREATE FINAL DISTILBERT ZIP
# ============================================================

import os
import shutil

PACKAGE_DIR = "distilbert_phishing_backend"
ZIP_NAME = "distilbert_phishing_backend"

# Create ZIP
zip_path = shutil.make_archive(
    ZIP_NAME,
    "zip",
    PACKAGE_DIR
)

print("ZIP CREATED SUCCESSFULLY")
print("========================")
print("File:", zip_path)

# Check file size
size_mb = os.path.getsize(zip_path) / (1024 * 1024)

print(f"Size: {size_mb:.2f} MB")

ZIP CREATED SUCCESSFULLY
========================
File: /content/distilbert_phishing_final/distilbert_phishing_backend.zip
Size: 235.86 MB

In [74]:
# ============================================================
# STEP 39: DOWNLOAD FINAL DISTILBERT PACKAGE
# ============================================================

from google.colab import files

files.download(
    "/content/distilbert_phishing_final/distilbert_phishing_backend.zip   "
)